language: objective-c
osx_image: xcode9
before_install:
- gem install cocoapods
- gem update fastlane --no-ri --no-rdoc --no-document
- git remote set-url origin "https://${GITHUB_TOKEN}@github.com/uias/Pageboy.git"
script: 
- .travis/build.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false