language: objective-c
osx_image: xcode8.2
before_install:
- gem update fastlane --no-ri --no-rdoc --no-document
script:
- fastlane test
after_success:
- fastlane deploy
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false